#!/bin/bash
#SBATCH --job-name=run_hangman_qwen3big
#SBATCH --output=logs/output/experiment-hm-qwen3big-%A.%a.out
#SBATCH --error=logs/error/experiment-hm-qwen3big-%A.%a.err
#SBATCH --time=7-00:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=32G
#SBATCH --partition=long-cpu

# Cd to project root
cd /home/mila/b/baldelld/scratch/hangman

# Create directories for logs
mkdir -p logs/output logs/error

# Activate the virtual environment
source .venv/bin/activate || true

echo "--- Starting Hangman Qwen3-32B Run (CPU-only) ---"
python run_experiment.py --run-config ./config/hangman_qwen3big_run.yaml

echo "--- Experiment finished ---"



